variable "deploy_network_manager" {
  type        = bool
  default     = true
  description = "A boolean flag to signal deployment of the Network Manager resource."
}

variable "deploy_in_region" {
  type = object({
    all_regions  = optional(bool, false)
    canada       = optional(bool, false) # ca-central-1
    frankfurt    = optional(bool, false) # eu-central-1
    ireland      = optional(bool, false) # eu-west-1
    london       = optional(bool, false) # eu-west-2
    mumbai       = optional(bool, false) # ap-south-1
    n_california = optional(bool, false) # us-west-1
    n_virginia   = optional(bool, false) # us-east-1
    ohio         = optional(bool, false) # us-east-2
    oregon       = optional(bool, false) # us-west-2
    osaka        = optional(bool, false) # ap-northeast-3
    paris        = optional(bool, false) # eu-west-3
    sao_paulo    = optional(bool, false) # sa-east-1
    seoul        = optional(bool, false) # ap-northeast-2
    singapore    = optional(bool, false) # ap-southeast-1
    stockholm    = optional(bool, false) # eu-north-1
    sydney       = optional(bool, false) # ap-southeast-2
    tokyo        = optional(bool, false) # ap-northeast-1
  })
  default = {
    all_regions  = false
    canada       = false
    frankfurt    = false
    ireland      = false
    london       = false
    mumbai       = false
    n_california = false
    n_virginia   = false
    ohio         = false
    oregon       = false
    osaka        = false
    paris        = false
    sao_paulo    = false
    seoul        = false
    singapore    = false
    stockholm    = false
    sydney       = false
    tokyo        = false
  }
  description = <<-EOT
    A map of boolean flags to determine which regions the Transit Gateway will
    be provisioned in. If `all_regions = true`, a Transit Gateway will be
    deployed in all listed AWS regions, whether the individual region is enabled
    or not.
  EOT
}

variable "tags" {
  type        = map(string)
  default     = {}
  description = <<-EOT
    Key-value tags for all resources. If configured with a provider
    `default_tags` configuration block present, tags with matching keys will
    overwrite those defined at the provider-level.
  EOT
}

variable "transit_gateway_bgp_asn" {
  type = object({
    canada       = optional(number)
    frankfurt    = optional(number)
    ireland      = optional(number)
    london       = optional(number)
    mumbai       = optional(number)
    n_california = optional(number)
    n_virginia   = optional(number)
    ohio         = optional(number)
    oregon       = optional(number)
    osaka        = optional(number)
    paris        = optional(number)
    sao_paulo    = optional(number)
    seoul        = optional(number)
    singapore    = optional(number)
    stockholm    = optional(number)
    sydney       = optional(number)
    tokyo        = optional(number)
  })
  default = {
    canada       = 64512
    frankfurt    = 64513
    ireland      = 64514
    london       = 64515
    mumbai       = 64516
    n_california = 64517
    n_virginia   = 64518
    ohio         = 64519
    oregon       = 64520
    osaka        = 64521
    paris        = 64522
    sao_paulo    = 64523
    seoul        = 64524
    singapore    = 64525
    stockholm    = 64526
    sydney       = 64527
    tokyo        = 64528
  }
  description = <<-EOT
    A map of BGP ASNs to be configured for the Transit Gateway in each region.
    The BGP ASN must be unique for each ASN in order to peer and route between
    them.
  EOT
}

variable "transit_gateway_peering" {
  type = object({
    full_mesh                  = optional(bool, false)
    canada_to_frankfurt        = optional(bool, false)
    canada_to_ireland          = optional(bool, false)
    canada_to_london           = optional(bool, false)
    canada_to_mumbai           = optional(bool, false)
    canada_to_n_california     = optional(bool, false)
    canada_to_n_virginia       = optional(bool, false)
    canada_to_ohio             = optional(bool, false)
    canada_to_oregon           = optional(bool, false)
    canada_to_osaka            = optional(bool, false)
    canada_to_paris            = optional(bool, false)
    canada_to_sao_paulo        = optional(bool, false)
    canada_to_seoul            = optional(bool, false)
    canada_to_singapore        = optional(bool, false)
    canada_to_stockholm        = optional(bool, false)
    canada_to_sydney           = optional(bool, false)
    canada_to_tokyo            = optional(bool, false)
    frankfurt_to_ireland       = optional(bool, false)
    frankfurt_to_london        = optional(bool, false)
    frankfurt_to_mumbai        = optional(bool, false)
    frankfurt_to_n_california  = optional(bool, false)
    frankfurt_to_n_virginia    = optional(bool, false)
    frankfurt_to_ohio          = optional(bool, false)
    frankfurt_to_oregon        = optional(bool, false)
    frankfurt_to_osaka         = optional(bool, false)
    frankfurt_to_paris         = optional(bool, false)
    frankfurt_to_sao_paulo     = optional(bool, false)
    frankfurt_to_seoul         = optional(bool, false)
    frankfurt_to_singapore     = optional(bool, false)
    frankfurt_to_stockholm     = optional(bool, false)
    frankfurt_to_sydney        = optional(bool, false)
    frankfurt_to_tokyo         = optional(bool, false)
    ireland_to_london          = optional(bool, false)
    ireland_to_mumbai          = optional(bool, false)
    ireland_to_n_california    = optional(bool, false)
    ireland_to_n_virginia      = optional(bool, false)
    ireland_to_ohio            = optional(bool, false)
    ireland_to_oregon          = optional(bool, false)
    ireland_to_osaka           = optional(bool, false)
    ireland_to_paris           = optional(bool, false)
    ireland_to_sao_paulo       = optional(bool, false)
    ireland_to_seoul           = optional(bool, false)
    ireland_to_singapore       = optional(bool, false)
    ireland_to_stockholm       = optional(bool, false)
    ireland_to_sydney          = optional(bool, false)
    ireland_to_tokyo           = optional(bool, false)
    london_to_mumbai           = optional(bool, false)
    london_to_n_california     = optional(bool, false)
    london_to_n_virginia       = optional(bool, false)
    london_to_ohio             = optional(bool, false)
    london_to_oregon           = optional(bool, false)
    london_to_osaka            = optional(bool, false)
    london_to_paris            = optional(bool, false)
    london_to_sao_paulo        = optional(bool, false)
    london_to_seoul            = optional(bool, false)
    london_to_singapore        = optional(bool, false)
    london_to_stockholm        = optional(bool, false)
    london_to_sydney           = optional(bool, false)
    london_to_tokyo            = optional(bool, false)
    mumbai_to_n_california     = optional(bool, false)
    mumbai_to_n_virginia       = optional(bool, false)
    mumbai_to_ohio             = optional(bool, false)
    mumbai_to_oregon           = optional(bool, false)
    mumbai_to_osaka            = optional(bool, false)
    mumbai_to_paris            = optional(bool, false)
    mumbai_to_sao_paulo        = optional(bool, false)
    mumbai_to_seoul            = optional(bool, false)
    mumbai_to_singapore        = optional(bool, false)
    mumbai_to_stockholm        = optional(bool, false)
    mumbai_to_sydney           = optional(bool, false)
    mumbai_to_tokyo            = optional(bool, false)
    n_california_to_n_virginia = optional(bool, false)
    n_california_to_ohio       = optional(bool, false)
    n_california_to_oregon     = optional(bool, false)
    n_california_to_osaka      = optional(bool, false)
    n_california_to_paris      = optional(bool, false)
    n_california_to_sao_paulo  = optional(bool, false)
    n_california_to_seoul      = optional(bool, false)
    n_california_to_singapore  = optional(bool, false)
    n_california_to_stockholm  = optional(bool, false)
    n_california_to_sydney     = optional(bool, false)
    n_california_to_tokyo      = optional(bool, false)
    n_virginia_to_ohio         = optional(bool, false)
    n_virginia_to_oregon       = optional(bool, false)
    n_virginia_to_osaka        = optional(bool, false)
    n_virginia_to_paris        = optional(bool, false)
    n_virginia_to_sao_paulo    = optional(bool, false)
    n_virginia_to_seoul        = optional(bool, false)
    n_virginia_to_singapore    = optional(bool, false)
    n_virginia_to_stockholm    = optional(bool, false)
    n_virginia_to_sydney       = optional(bool, false)
    n_virginia_to_tokyo        = optional(bool, false)
    ohio_to_oregon             = optional(bool, false)
    ohio_to_osaka              = optional(bool, false)
    ohio_to_paris              = optional(bool, false)
    ohio_to_sao_paulo          = optional(bool, false)
    ohio_to_seoul              = optional(bool, false)
    ohio_to_singapore          = optional(bool, false)
    ohio_to_stockholm          = optional(bool, false)
    ohio_to_sydney             = optional(bool, false)
    ohio_to_tokyo              = optional(bool, false)
    oregon_to_osaka            = optional(bool, false)
    oregon_to_paris            = optional(bool, false)
    oregon_to_sao_paulo        = optional(bool, false)
    oregon_to_seoul            = optional(bool, false)
    oregon_to_singapore        = optional(bool, false)
    oregon_to_stockholm        = optional(bool, false)
    oregon_to_sydney           = optional(bool, false)
    oregon_to_tokyo            = optional(bool, false)
    osaka_to_paris             = optional(bool, false)
    osaka_to_sao_paulo         = optional(bool, false)
    osaka_to_seoul             = optional(bool, false)
    osaka_to_singapore         = optional(bool, false)
    osaka_to_stockholm         = optional(bool, false)
    osaka_to_sydney            = optional(bool, false)
    osaka_to_tokyo             = optional(bool, false)
    paris_to_sao_paulo         = optional(bool, false)
    paris_to_seoul             = optional(bool, false)
    paris_to_singapore         = optional(bool, false)
    paris_to_stockholm         = optional(bool, false)
    paris_to_sydney            = optional(bool, false)
    paris_to_tokyo             = optional(bool, false)
    sao_paulo_to_seoul         = optional(bool, false)
    sao_paulo_to_singapore     = optional(bool, false)
    sao_paulo_to_stockholm     = optional(bool, false)
    sao_paulo_to_sydney        = optional(bool, false)
    sao_paulo_to_tokyo         = optional(bool, false)
    seoul_to_singapore         = optional(bool, false)
    seoul_to_stockholm         = optional(bool, false)
    seoul_to_sydney            = optional(bool, false)
    seoul_to_tokyo             = optional(bool, false)
    singapore_to_stockholm     = optional(bool, false)
    singapore_to_sydney        = optional(bool, false)
    singapore_to_tokyo         = optional(bool, false)
    stockholm_to_sydney        = optional(bool, false)
    stockholm_to_tokyo         = optional(bool, false)
    sydney_to_tokyo            = optional(bool, false)
  })
  default = {
    full_mesh                  = false
    canada_to_frankfurt        = false
    canada_to_ireland          = false
    canada_to_london           = false
    canada_to_mumbai           = false
    canada_to_n_california     = false
    canada_to_n_virginia       = false
    canada_to_ohio             = false
    canada_to_oregon           = false
    canada_to_osaka            = false
    canada_to_paris            = false
    canada_to_sao_paulo        = false
    canada_to_seoul            = false
    canada_to_singapore        = false
    canada_to_stockholm        = false
    canada_to_sydney           = false
    canada_to_tokyo            = false
    frankfurt_to_ireland       = false
    frankfurt_to_london        = false
    frankfurt_to_mumbai        = false
    frankfurt_to_n_california  = false
    frankfurt_to_n_virginia    = false
    frankfurt_to_ohio          = false
    frankfurt_to_oregon        = false
    frankfurt_to_osaka         = false
    frankfurt_to_paris         = false
    frankfurt_to_sao_paulo     = false
    frankfurt_to_seoul         = false
    frankfurt_to_singapore     = false
    frankfurt_to_stockholm     = false
    frankfurt_to_sydney        = false
    frankfurt_to_tokyo         = false
    ireland_to_london          = false
    ireland_to_mumbai          = false
    ireland_to_n_california    = false
    ireland_to_n_virginia      = false
    ireland_to_ohio            = false
    ireland_to_oregon          = false
    ireland_to_osaka           = false
    ireland_to_paris           = false
    ireland_to_sao_paulo       = false
    ireland_to_seoul           = false
    ireland_to_singapore       = false
    ireland_to_stockholm       = false
    ireland_to_sydney          = false
    ireland_to_tokyo           = false
    london_to_mumbai           = false
    london_to_n_california     = false
    london_to_n_virginia       = false
    london_to_ohio             = false
    london_to_oregon           = false
    london_to_osaka            = false
    london_to_paris            = false
    london_to_sao_paulo        = false
    london_to_seoul            = false
    london_to_singapore        = false
    london_to_stockholm        = false
    london_to_sydney           = false
    london_to_tokyo            = false
    mumbai_to_n_california     = false
    mumbai_to_n_virginia       = false
    mumbai_to_ohio             = false
    mumbai_to_oregon           = false
    mumbai_to_osaka            = false
    mumbai_to_paris            = false
    mumbai_to_sao_paulo        = false
    mumbai_to_seoul            = false
    mumbai_to_singapore        = false
    mumbai_to_stockholm        = false
    mumbai_to_sydney           = false
    mumbai_to_tokyo            = false
    n_california_to_n_virginia = false
    n_california_to_ohio       = false
    n_california_to_oregon     = false
    n_california_to_osaka      = false
    n_california_to_paris      = false
    n_california_to_sao_paulo  = false
    n_california_to_seoul      = false
    n_california_to_singapore  = false
    n_california_to_stockholm  = false
    n_california_to_sydney     = false
    n_california_to_tokyo      = false
    n_virginia_to_ohio         = false
    n_virginia_to_oregon       = false
    n_virginia_to_osaka        = false
    n_virginia_to_paris        = false
    n_virginia_to_sao_paulo    = false
    n_virginia_to_seoul        = false
    n_virginia_to_singapore    = false
    n_virginia_to_stockholm    = false
    n_virginia_to_sydney       = false
    n_virginia_to_tokyo        = false
    ohio_to_oregon             = false
    ohio_to_osaka              = false
    ohio_to_paris              = false
    ohio_to_sao_paulo          = false
    ohio_to_seoul              = false
    ohio_to_singapore          = false
    ohio_to_stockholm          = false
    ohio_to_sydney             = false
    ohio_to_tokyo              = false
    oregon_to_osaka            = false
    oregon_to_paris            = false
    oregon_to_sao_paulo        = false
    oregon_to_seoul            = false
    oregon_to_singapore        = false
    oregon_to_stockholm        = false
    oregon_to_sydney           = false
    oregon_to_tokyo            = false
    osaka_to_paris             = false
    osaka_to_sao_paulo         = false
    osaka_to_seoul             = false
    osaka_to_singapore         = false
    osaka_to_stockholm         = false
    osaka_to_sydney            = false
    osaka_to_tokyo             = false
    paris_to_sao_paulo         = false
    paris_to_seoul             = false
    paris_to_singapore         = false
    paris_to_stockholm         = false
    paris_to_sydney            = false
    paris_to_tokyo             = false
    sao_paulo_to_seoul         = false
    sao_paulo_to_singapore     = false
    sao_paulo_to_stockholm     = false
    sao_paulo_to_sydney        = false
    sao_paulo_to_tokyo         = false
    seoul_to_singapore         = false
    seoul_to_stockholm         = false
    seoul_to_sydney            = false
    seoul_to_tokyo             = false
    singapore_to_stockholm     = false
    singapore_to_sydney        = false
    singapore_to_tokyo         = false
    stockholm_to_sydney        = false
    stockholm_to_tokyo         = false
    sydney_to_tokyo            = false
  }
  description = <<-EOT
    A map of peering connections to be configured for the Transit Gateways in
    each region. If `full_mesh = true`, a Transit Gateway peering connection
    will be provisioned between all listed AWS regions, to form a full mesh of
    connectivity, whether and individual peering is enabled or not. If a peering
    connection is enabled, but a Transit Gateway is not provisioned in both
    regions, the peering connection will not be established.
  EOT
}
